//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace donnee
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class Vent
    {
        public Vent(double u, double v)
        {
            this.Direction = conversion.Conversion.directionVent(u, v);
            this.U = u;
            this.V = v;
            this.Vitesse = conversion.Conversion.vitesseVent(u, v);
        }

        public virtual double U
        {
            get;
            set;
        }

        public virtual double V
        {
            get;
            set;
        }

        public virtual double Vitesse
        {
            get;
            set;
        }

        public virtual double Direction
        {
            get;
            set;
        }

        override public String ToString()
        {
            String res = String.Empty;
            res += "dir: " + this.Direction + " v: " + this.Vitesse;
            return res;
        }

    }
}

