//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Instant
{
	public virtual int Annee
	{
		get;
		set;
	}

	public virtual int Mois
	{
		get;
		set;
	}

	public virtual int Jour
	{
		get;
		set;
	}

	public virtual int Heure
	{
		get;
		set;
	}

	public virtual IEnumerable<Point> Point
	{
		get;
		set;
	}

}

