//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Point
{
	public virtual double Longitude
	{
		get;
		set;
	}

	public virtual double Latitude
	{
		get;
		set;
	}

	public virtual double Pression
	{
		get;
		set;
	}

	public virtual Vent Vent
	{
		get;
		set;
	}

}

