//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Previsions
{
	public virtual IEnumerable<Instant> Instant
	{
		get;
		set;
	}

	public virtual Point ajoutPoint(Instant instant, double latitude, double longitude, double pression)
	{
        Point unPoint = new Point();
        unPoint.Latitude = latitude;
        unPoint.Longitude = longitude;
        unPoint.Pression = pression;
        instant.lesPoints.ToList<Point>().Add(unPoint);
        return unPoint;
	}

	public virtual Instant ajoutInstant(int annee, int mois, int jour, int heure)
	{
		throw new System.NotImplementedException();
	}

	public virtual Vent ajoutVent(Instant instant, Point donnee, double direction, double u, double v, double vitesse)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool modifierZone(Point donnee, Point nouvelle)
	{
		throw new System.NotImplementedException();
	}

	public virtual Point getPoint(Instant instant, double latitude, double longitude)
	{
		throw new System.NotImplementedException();
	}

	public virtual Vent getVent(Instant instant, Point donnee)
	{
		throw new System.NotImplementedException();
	}

	public virtual Vent getVent(Instant instant, double latitude, double longitude)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool modifierZone(Point donnee, double latitude, double longitude, double pression, Vent vent)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool modifierVent(Vent vent, Vent nouveau)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool modifierVent(Vent vent, Point donnee, double direction, double u, double v, double vitesse)
	{
		throw new System.NotImplementedException();
	}

	public virtual IEnumerable<Point> getZone(Instant instant, Point X1, Point X2)
	{
		throw new System.NotImplementedException();
	}

}

