//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Vent
{
	public virtual double U
	{
		get;
		set;
	}

	public virtual double V
	{
		get;
		set;
	}

	public virtual double Vitesse
	{
		get;
		set;
	}

	public virtual double Direction
	{
		get;
		set;
	}

}

