//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace donnee
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum TypeVitesseVent : int
	{
		KilometreHeure = 0,
		Noeud = 1,
		Beaufort = 2,
	}
}
