//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Donnee
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Date
	{
        public Date (int a, int m, int j, int h)
        {
            this.Annee = a;
            this.Mois = m;
            this.Jour = j;
            this.Heure = h;
            this.lesPoints = null;
        }
		public virtual int Annee
		{
			get;
			set;
		}

		public virtual int Mois
		{
			get;
			set;
		}

		public virtual int Jour
		{
			get;
			set;
		}

		public virtual int Heure
		{
			get;
			set;
		}

		public virtual IList<Point> lesPoints
		{
			get;
			set;
		}

		public virtual Point recherchePoint(double latitude, double longitude)
		{
			foreach (Point unPoint in lesPoints)
            {
                if ((unPoint.Latitude == latitude) && (unPoint.Longitude == longitude))
                {
                    return unPoint;
                }
            }
            return null;
		}

	}
}

