//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Donnee
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Point
	{
        public Point (double latitude, double longitude, Vent vent, double pression)
        {
            this.Latitude = latitude;
            this.Longitude = longitude;
            this.leVent = vent;
            this.Pression = pression;
        }
		public virtual double Longitude
		{
			get;
			set;
		}

		public virtual double Latitude
		{
			get;
			set;
		}

		public virtual double Pression
		{
			get;
			set;
		}

		public virtual Vent leVent
		{
			get;
			set;
		}

	}
}

