//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Donnee
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Vent
	{
        public Vent (double dir, double u, double v, double vit) {
            this.Direction = dir;
            this.U = u;
            this.V = v;
            this.Vitesse = vit;
        }

		public virtual double U
		{
			get;
			set;
		}

		public virtual double V
		{
			get;
			set;
		}

		public virtual double Vitesse
		{
			get;
			set;
		}

		public virtual double Direction
		{
			get;
			set;
		}

        public String toString()
        {
            String res = null;
            res += "dir: " + this.Direction + " v: " + this.Vitesse;
            return res;
        }

	}
}

