//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Class2
{
	public virtual object test2
	{
		get;
		set;
	}

	public virtual void fist3()
	{
		throw new System.NotImplementedException();
	}

}

